### ISSUE TITLE
[FEATURE REQUEST] Add Arm64v8 support for Docker

### ISSUE THREAD

**Issue by CrimsonTome** [hullcss/hullcss-discord-bot#189]
### Is your feature request related to a problem?

HullCSS bot does not run on ARM based servers because it is only built for amd64

### What solution would you like?

Add an alternative Dockerfile for ARM and a GH action to build and publish

### What alternatives have you considered?

Running through regular NodeJS and a Systemd service

### Do you have any additional context?

N/A

**Comment by KieranRobson** [comment]
Implemented in Commits: 157ee15d9be544de76d811230215b179d389db10 and ae14b890a841edd0a830d5eeb06f6d2f4b987b66

**Comment by CrimsonTome** [comment]
Can confirm it works, had to remove the old amd64 image that was still there. Thank you.
