### ISSUE TITLE
[FEATURE REQUEST] Change to the bot introduction message

### ISSUE THREAD

**Issue by alex8obrien** [hullcss/hullcss-discord-bot#206]
### Is your feature request related to a problem?

The bot does not remind new users to fill out a paid memeber request message

### What solution would you like?

Edit the bot message to say: "Hi @USER welcome to the HullCSS discord sever. Please be sure to fill out your roles in #roles, sumbit a paid member request in #paid-member-request and introduce yourself in #introductions"

### What alternatives have you considered?

None because this is a good issue

### Do you have any additional context?

Nope

**Comment by KieranRobson** [comment]
Implemented in https://github.com/hullcss/hullcss-discord-bot/commit/79db6a670e62e7716aaa31af2cf4cf59ffbb8321
