### ISSUE TITLE
Feature request - templates

### ISSUE THREAD

**Issue by CrimsonTome** [hullcss/hullcss-discord-bot#5]
more of a meta thing but PR and issue templates for feature requests, complaints or bug reports etc

**Comment by KieranRobson** [comment]
Will work on this tomorrow and get both PR and Issue templates created

**Comment by KieranRobson** [comment]
Implemented:
https://github.com/hullcss/hullcss-discord-bot/issues/new/choose
https://github.com/hullcss/hullcss-discord-bot/blob/main/.github/PULL_REQUEST_TEMPLATE.md
