### ISSUE TITLE
[FEATURE REQUEST] Output event data from Discord to file

### ISSUE THREAD

**Issue by CrimsonTome** [hullcss/hullcss-discord-bot#8]
### Is your feature request related to a problem?
I need an easy way to import event data into the [HullCSS website](https://hullcss.org) from the [repo](https://github.com/hullcss/hullcss-site-jet).  

### What solution would you like?
Send output from bot event creation to a file e.g. `.json` or even `.txt`. Something that I can easily perform queries on to format it into markdown or pure html. Bonus points if you can do the formatting for me, so exporting nicely into `.md` or `.html`.

### What alternatives have you considered?
~~Doing it myself~~ 

### Do you have any additional context?
N/A

**Comment by KieranRobson** [comment]
Implemented in https://github.com/hullcss/hullcss-discord-bot/commit/595806866ac3a374d2bc0578f1e89784db422690
